### ISSUE TITLE
Failed to resolve: com.github.zjutkz:Weex-OkHttp-Adapter:1.1

### ISSUE THREAD

**Issue by cnmao** [zjutkz/Weex-OkHttp-Adapter#3]
![image](https://user-images.githubusercontent.com/15217841/56558550-a908b080-65d1-11e9-8208-a8a5ed038d3e.png)

**Comment by zjutkz** [comment]
@cnmao 你好，请问jitpack的地址加了吗？

**Comment by cnmao** [comment]
添加了  直接把你代码下载下来， 添加进去了 ！！！
